# Base configs
baseurl: "https://photography.nrshapiro.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Neil Shapiro"
subtitle: "See the world through my eyes (draft site)!"
author: "Neil Shapiro"
header:
 title: "Photography"
 subtitle: "by Neil R. Shapiro"
footer:
 name: "Hey there, my name is Neil R. Shapiro"
 bio: "I am a photographer and developer."
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/fineartbynature"
  twitter: "https://www.twitter.com/ram__patra"
  instagram: "https://www.instagram.com/ram_patra"
  dribbble: "https://dribbble.com/rampatra"
  linkedin: "https://in.linkedin.com/in/ram-patra"
  github: "https://www.github.com/rampatra"
